### ISSUE TITLE
Alliance - Worgan start area has no mobs or quests

### ISSUE THREAD

**Issue by Northernn** [holydeew/KyrianCORE-bugtracker#10]
cannot get out of the start area - no npcs or quests, or portals

**Comment by Northernn** [comment]
Seems most of the starting areas are not playable, no quests, or quests break by the second or third quest, if you have to loot something, or follow someone, or mount something, it just doesn't work so you cannot go any further.

**Comment by Thordekk** [comment]
Fixed
