### ISSUE TITLE
Zeppelin from Thunderbluff to Orgrimmar 

### ISSUE THREAD

**Issue by Northernn** [holydeew/KyrianCORE-bugtracker#2]
Zeppelin from Thunderbluff to Orgrimmar  just gets stuck in a loop, never gets to destination, you have to jump off the ship.

**Comment by nicknewbold** [comment]
If you stay on it and wait, it finally docks in orgrimmar after around 3 or 4 loops between northern barens and mulgore

**Comment by Thordekk** [comment]
FIxed
