### ISSUE TITLE
Eversong Woods Mobs Level Scaling Error

### ISSUE THREAD

**Issue by WolfAndMoon114** [holydeew/KyrianCORE-bugtracker#20]
Level Scaling for Eversong Woods is somewhat broken; some enemies will spawn at level 10+, whereas they are supposed to spawn at your current level. 
For example: NPC ID 15638 (Arcane Patroller), NPC ID 15644 (Wretched Urchin) can spawn from my current level up to 20+

**Comment by Shimmergloom84** [comment]
Pretty easy fix.

Open DB and pull out the creature table into a .csv
Do the same from the Wow.Tools Creature table.
vlookup tuningID from wow.tools table into the creature table
Remove duplicates - and inject entry + tuning ID into the creature tuning DB.

Worked like a charm for me.
Let me know if you would like a more in depth explaination.
